spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpa
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
#      更新或者创建数据表
      ddl-auto: update
#      控制台显示sql
    show-sql: true
server:
  servlet:
    context-path: /jpa
